---
title: "Packages"
output: html_document
date: "2023-02-12"
editor_options: 
  chunk_output_type: console
---

```{r set-up-renv, echo = FALSE, results = FALSE, message = FALSE, cache = FALSE}

# --- SET UP THE PACKAGE "renv" FOR A REPRODUCIBILE ENVIRONMENT --- #

# Install the package "renv" if it's not installed yet. Renv allows you to 
# reinstall the specific package versions that were used when writing code for 
# this project. 

if (!requireNamespace("renv", quietly = TRUE)) {
  install.packages("renv")
}
 
# Reinstall the specific package versions that were used when writing code for 
# this project. 

# setwd("..")
# renv::restore()
```

```{r load-packages, echo = FALSE, results = FALSE, message = FALSE, cache = FALSE}

# --- LOAD PACKAGES --- #

#General computing
library("here")
library("testthat")
library("renv")

#Data manipulation
library("data.table")
library("plyr")
library("tidyverse")

#Data visualisation
library("ggpubr") #ggarrange
library("plotly")
library("rempsyc")
library("broom")
library("officer")
library("ggforce") # for creating geometrical shapes

#Data analysis
library("lmerTest") #To use mixed effects models that get you p-values and F statistics
library("glmmTMB") #To use mixed effects models that can fit Tweedie distributions for biomass data
library("optimx") #To optimise lmerTest algorithms
library("vegan")
library("betapart")
library("Rmisc") #For summarySE
library("combinat")
library("emmeans") #For contrasts in a lmer object. An alternative is multcomp.
library("bemovi")
library("e1071") #For support vector machines to do species ID 
library("SingleCaseES") #For the log response ratio
library("gllvm") #To run gllvmms

#Conflicts
library("conflicted")
```

```{r}

# --- SOLVE PACKAGE CONFLICTS --- #

conflict_prefer("load", "base")
conflict_prefer("filter", "dplyr")
conflict_prefer("mutate", "dplyr")
conflict_prefer("summarise", "dplyr")
conflict_prefer("rename", "dplyr")
conflict_prefer("arrange", "dplyr")
conflict_prefer("here", "here")
conflict_prefer("combn", "combinat")
conflict_prefer("anova", "lmerTest")
conflicts_prefer(lmerTest::lmer)
conflicts_prefer(dplyr::select)
```