---
title: "Analyse meta-ecosystem biomass"
output: html_document
date: "2023-11-28"
editor_options: 
  chunk_output_type: console
---

#### Biomass {.tabset .tabset-pills}

```{r define-response-variables-metaecos}

# --- DEFINE RESPONSE VARIABLE --- #

response_variable_selected = "total_metaecosystem_bioarea_mm2"
```

<details  open = "open">
<summary>Plot original data - means</summary>
```{r plot-original-data-metaecos}

# --- PLOT ORIGINAL DATA --- #

plot.metaecos.points(ds_metaecosystems,
                     response_variable_selected,
                     3)
```
</details>

<details>
<summary>Prepare data for analysis</summary>
```{r prepare-data-for-analysis-metaecos}

# --- PREPARE DATA FOR ANALYSIS --- #

# Add baselines

baselines = ds_metaecosystems %>%
  filter(time_point == time_point_of_baselines) %>%
  select(system_nr,
         all_of(response_variable_selected)) %>%
  rename(baseline = all_of(response_variable_selected))

data_for_analysis = ds_metaecosystems %>%
  left_join(baselines)

# Filter

data_for_analysis = data_for_analysis %>%
  filter(time_point %in% time_points_model,
         !is.na(!!sym(response_variable_selected)))
```
</details>

<details>
<summary>Plot data for analysis - means</summary>
```{r plot-data-for-analysis-metaecos}

# --- PLOT DATA FOR ANALYSIS --- #

plot.metaecos.points(data_for_analysis,
                     response_variable_selected,
                     3)
```
</details>

<details>
<summary>Compute model results</summary>
```{r define-nr-of-boostrap-iterations}

# --- DEFINE NR OF BOOTSTRAP ITERATIONS --- #

bootstrap_iterations = 10
```

```{r compute-stats-for-all-ecosystem-combinations, eval = recompute_metaeco_analysis}

# --- COMPUTE STATS FOR ALL ECOSYSTEM COMBINATIONS --- #

# If you see "Warning in (function (iprint = 0L, maxfun = 10000L, 
# FtolAbs = 1e-05, FtolRel = ## 1e-15, : unused control arguments ignored", 
# ignore it. It just means that you didn't pass the control argument to the 
# Nelder_Mead optimiser, so it uses the default.

# Initialise lists

set_data_for_analysis = list()
coefficients = list()
full_model = list()

# Get the number of rows in the sets_of_sets data frame

n_sets_of_sets = nrow(sets_of_sets)

# Generate random sets of indices for bootstrap iterations

random_nrs <- runif(bootstrap_iterations, 
                              min = 1, 
                              max = n_sets_of_sets) %>% round()

# Set the optimizer inputs for model fitting

optimizer_input = "optimx"
method_input = "L-BFGS-B"

# Loop through each randomly selected set of sets

for (i in 1:length(random_nrs)) {

  # Get the current set of sets based on the random index
  
  sets = sets_of_sets[random_nrs[i],]
  
  # Identify system numbers that are unconnected based on the metaecosystem type
  
  unconnected_system_nrs = unconnected_combinations_sets %>%
    filter((metaeco_type_n_connection == "autotrophic-dominated unconnected" & 
            set == sets$autotrophic_dominated_set_n) |
           (metaeco_type_n_connection == "equally-dominated unconnected" & 
            set == sets$equally_dominated_set_n) |
           (metaeco_type_n_connection == "heterotrophic-dominated unconnected" & 
            set == sets$heterotrophic_dominated_set_n)) %>%
    pull(system_nr)  # Extract system numbers from the filtered data
  
  # Filter the data for analysis based on connection status and unconnected systems
  
  set_data_for_analysis[[i]] = data_for_analysis %>%
    filter(connection == "connected" | system_nr %in% unconnected_system_nrs)
  
  # Fit a generalized linear mixed model with a Tweedie distribution
  # This is a try. I changed the lmer model with a tweedie glmmtmb.
  
  full_model[[i]] = glmmTMB::glmmTMB(get(response_variable_selected) ~
                                            metaecosystem_type * connection +  
                                            (1 | day) +
                                            (1 | baseline),                         
                                          data = set_data_for_analysis[[i]], 
                                          REML = FALSE,                        
                                          family = glmmTMB::tweedie(link = "log"))
  
  # Extract and store the coefficients from the model summary
  
  coefficients[[i]] = summary(full_model[[i]])[["coefficients"]]
}

# Save the results

save(bootstrap_iterations,
     file = here("..",
                 "3_results", 
                 "mixed_effect_models", 
                 "metaeco_analysis_n_of_bootstrap_iterations.RData"))

save(random_nrs,
     file = here("..",
                 "3_results", 
                 "mixed_effect_models", 
                 "metaeco_analysis_bootstrapped_sets_of_sets.RData"))

save(coefficients,
     file = here("..",
                 "3_results", 
                 "mixed_effect_models", 
                 "metaeco_analysis_bootstrapped_model_coefficients.RData"))
```

```{r load-results}

# --- LOAD RESULTS --- #

load(file = here("..",
                 "3_results", 
                 "mixed_effect_models", 
                 "metaeco_analysis_n_of_bootstrap_iterations.RData"))

load(file = here("..",
                 "3_results", 
                 "mixed_effect_models", 
                 "metaeco_analysis_bootstrapped_sets_of_sets.RData"))

load(file = here("..",
                 "3_results", 
                 "mixed_effect_models", 
                 "metaeco_analysis_bootstrapped_model_coefficients.RData"))
```
</details>

<details>
<summary>Show single combination results</summary>
```{r model-residuals-metaecos}

# --- SHOW MODEL RESIDUALS --- #

create.res.vs.fit.metaecos(full_model[[1]],
                           set_data_for_analysis[[i]])

qqnorm(resid(full_model[[1]]))
qqline(resid(full_model[[1]]))
```

```{r model-summary-metaecos}

# --- SHOW MODEL SUMMARY --- #

print(summary(full_model[[1]]), digits = 3)
```

```{r model-anova-metaecos}

# --- SHOW MODEL ANOVA --- #

anova_output = car::Anova(full_model[[1]], type = "III")
```

```{r get-model-contrasts-metaecos}

# --- GET MODEL CONSTRASTS --- #

emmeans_output = emmeans(full_model[[1]],
                         specs = pairwise ~ metaecosystem_type:connection,
                         adjust = "tukey",
                         bias.adj = TRUE,
                         lmer.df = "satterthwaite")
emmeans_output

# Give a name for each level which you want to compare

AD_unconnected = c(1, 0, 0, 0, 0, 0)
ED_unconnected = c(0, 1, 0, 0, 0, 0)
HD_unconnected = c(0, 0, 1, 0, 0, 0)
AD_connected = c(0, 0, 0, 1, 0, 0)
ED_connected = c(0, 0, 0, 0, 1, 0)
HD_connected = c(0, 0, 0, 0, 0, 1)

# Compute the contrasts

n_of_digits = 3
contrasts = contrast(emmeans_output, 
         method = list("auto-dom connection effect" = AD_connected - AD_unconnected,
                       "equally-dom connection effect" = ED_connected - ED_unconnected,
                       "hetero-dom connection effect" = HD_connected - HD_unconnected,
                       "auto- vs equally-dom connected" = AD_connected - ED_connected,
                       "hetero- vs equally-dom connected" = HD_connected - ED_connected,
                       "auto- vs equally-dom unconnected" = AD_unconnected - ED_unconnected,
                       "hetero- vs equally-dom unconnected" = HD_unconnected - ED_unconnected)) %>%
  as.data.frame() %>%
  mutate(p.value = round(p.value, digits = n_of_digits),
         estimate = round(estimate, digits = n_of_digits),
         SE = round(SE, digits = n_of_digits),
         df = round(df, digits = n_of_digits),
         z.ratio = round(z.ratio, digits = n_of_digits),
         e = "",
         e = ifelse(p.value > 0.1, 
                           "",
                           e),
         e = ifelse(p.value < 0.05, 
                           "*",
                           e),
         e = ifelse(p.value < 0.01, 
                           "**",
                           e),
         e = ifelse(p.value < 0.001, 
                           "***",
                           e)) %>%
  rename(" " = e)
```
</details>

<details  open = "open">
<summary>Show single combination ANOVA & contrasts</summary>
```{r show-model-contrasts-metaecos}

# --- SHOW MODEL RESULTS FOR A SINGLE COMBINATIONS --- #

anova_output
contrasts
```
</details>

<details>
<summary>Show all combinations results</summary>
```{r}

# --- SHOW WHICH RANDOM SETS OF SETS HAVE BOOTSTRAPPED --- #

# Show to make sure that there's no bias in which ecosystem combinations have
# been combined. 

hist(random_nrs,
     main = "Random sets of sets used for bootrapping")
```

```{r}

# --- CALCULATE THE CONTRASTS FOR ALL ECOSYSTEM COMBINATIONS --- #

# Initialise lists

ANOVA_output = list()
emmeans_output = list()
contrasts = list()

# Loop through the sets of sets to calculate their contrasts

for (i in 1:length(random_nrs)){
  
  # Perform ANOVA
  
  ANOVA_output[[i]] = car::Anova(full_model[[i]]) %>%
    as.data.frame() %>%
    mutate(variable = rownames(.))
  
  colnames(ANOVA_output[[i]]) = c("Chisq",
                                       "Df",
                                       "p",
                                       "variable")
  
  # Compute estimated marginal means (EMMeans) for the interaction of 
  # metaecosystem type and connection
  
  emmeans_output[[i]] = emmeans(full_model[[i]],
                                     specs = pairwise ~ metaecosystem_type:connection,
                                     adjust = "tukey",
                                     bias.adj = TRUE,
                                     lmer.df = "satterthwaite")
  
  AD_unconnected = c(1, 0, 0, 0, 0, 0)
  ED_unconnected = c(0, 1, 0, 0, 0, 0)
  HD_unconnected = c(0, 0, 1, 0, 0, 0)
  AD_connected = c(0, 0, 0, 1, 0, 0)
  ED_connected = c(0, 0, 0, 0, 1, 0)
  HD_connected = c(0, 0, 0, 0, 0, 1)
  
  contrasts[[i]] = contrast(emmeans_output[[i]], 
                       method = list("auto-dom connection effect" = AD_connected - AD_unconnected,
                                     "equally-dom connection effect" = ED_connected - ED_unconnected,
                                     "hetero-dom connection effect" = HD_connected - HD_unconnected,
                                     "auto- vs equally-dom connected" = AD_connected - ED_connected,
                                     "heterotrophic- vs equally-dom connected" = HD_connected - ED_connected,
                                     "auto- vs equally-dom unconnected" = AD_unconnected - ED_unconnected,
                                     "heterotrophic- vs equally-dom unconnected" = HD_unconnected - ED_unconnected)) %>%
    as.data.frame() 
  
  contrast_levels = contrasts[[i]]$contrast

}


# Average ANOVA across sets of sets 

ANOVA = do.call(rbind, ANOVA_output) %>%
  group_by(variable) %>%
  summarise(Chisq = round(mean(Chisq), digits = 1),
            Df = round(mean(Df), digits = 1),
            p = round(mean(p), digits = 4)) %>%
  mutate(variable = factor(variable,
                           levels = c("metaecosystem_type",
                                      "connection",
                                      "metaecosystem_type:connection"))) %>%
  arrange(variable)

# Average the contrasts across sets of sets 

contrasts = do.call(rbind, contrasts) %>%
  group_by(contrast) %>%
  summarise(estimate = round(mean(estimate), digits = 1),
            SE = round(mean(SE), digits = 1),
            df = round(mean(df), digits = 0),
            z.ratio = round(mean(z.ratio), digits = 2),
            p.value = round(mean(p.value), digits = 4)) %>%
  mutate(contrast = factor(contrast,
                           levels = c("auto-dom connection effect",
                                     "equally-dom connection effect",
                                     "hetero-dom connection effect",
                                     "auto- vs equally-dom connected",
                                     "hetero- vs equally-dom connected",
                                     "auto- vs equally-dom unconnected",
                                     "hetero- vs equally-dom unconnected"))) %>%
  arrange(contrast)
```
</details>

<details>
<summary>Show all combinations ANOVA & contrasts</summary>
```{r}

# --- SHOW MODEL RESULTS FOR ALL COMBINATIONS --- #

ANOVA
contrasts
```
</details>
