---
title: "Untitled"
output: html_document
date: "2023-11-28"
editor_options: 
  chunk_output_type: console
---

<details  open = "open">
<summary>Plot original data - means</summary>
```{r}

# --- PLOT ORIGINAL DATA WITH MEANS --- #

plot = plot.ecosystems.points(ds_ecosystems %>% 
                                filter(trophic_type == trophy_selected),
                              response_variable_selected,
                              legend_row_n_input = 3)
plot
```
</details>

<details>
<summary>Plot original data - replicates</summary>
```{r}

# --- PLOT ORIGINAL DATA WITH SINGLE REPLICATES --- #

plot.ecosystems.replicates.one.by.one(ds_ecosystems,
                                      ecosystem_size_and_trophy_selected,
                                      response_variable_selected)
```
</details>

<details>
<summary>Prepare data for analysis</summary>
```{r}

# --- PREPARE DATA FOR ANALYSIS --- #

# Add baselines

baselines = ds_ecosystems %>%
  filter(time_point == time_point_of_baselines) %>%
  select(ecosystem_ID,
         all_of(response_variable_selected)) %>%
  rename(baseline = all_of(response_variable_selected))

data_for_analysis = ds_ecosystems %>%
  left_join(baselines)

# Filter data

data_for_analysis = data_for_analysis %>%
  filter(trophic_type == trophy_selected,
         time_point %in% time_points_model,
         !is.na(!!sym(response_variable_selected))) %>%
  mutate(ecosystem_ID = as.character(ecosystem_ID),
         size = NA,
         size = case_when(ecosystem_size == "small" ~ "S",
                          ecosystem_size == "medium" ~ "M",
                          ecosystem_size == "large" ~ "L",
                          TRUE ~ size),
         size = factor(size, levels = c("S", "M", "L")),
         size = as.character(size))
```
</details>

<details>
<summary>Plot data for analysis - means</summary>
```{r}

# --- PLOT DATA FOR ANALYSIS WITH MEANS --- #

plot.ecosystems.points(data_for_analysis,
                       response_variable_selected,
                       legend_row_n_input = 3)
```
</details>

<details>
<summary>Plot data for analysis - replicates</summary>
```{r}

# --- PLOT DATA FOR ANALYSIS WITH SINGLE REPLICATES --- #

plot.ecosystems.replicates.one.by.one(data_for_analysis,
                                      ecosystem_size_and_trophy_selected,
                                      response_variable_selected)
```
</details>

<details>
<summary>Compute model results</summary>

```{r}

# --- DEFINE FORMULA --- #

formula = paste("get(response_variable_selected) ~",
                "size * connection +",
                "(1 | baseline) +",
                "(1 | day)") %>%
  print()

formula = as.formula(formula)
```

```{r eval = (distribution_selected == "gaussian"), echo = (distribution_selected == "gaussian")}

# --- CREATE MODEL (WITH NORMAL DISTRIBUTION) --- #
  
 model = lmer(formula,
             data = data_for_analysis,
             REML = FALSE,
             control = lmerControl(optimizer = "Nelder_Mead"))
```

```{r eval = (distribution_selected == "tweedie"), echo = (distribution_selected == "tweedie")}

# --- CREATE MODEL (WITH TWEEDIE DISTRIBUTION) --- #


if(trophy_selected != "heterotrophic" && response_variable_selected != "median_body_size_µm2"){
  

  model <- glmmTMB::glmmTMB(formula,
                            data = data_for_analysis,
                            family = glmmTMB::tweedie(link = "log"))
}

if(trophy_selected == "heterotrophic" && response_variable_selected == "median_body_size_µm2"){
  
 model <- glmmTMB(formula,
                  data = data_for_analysis,
                  family = glmmTMB::tweedie(link = "log"),
                  control = glmmTMBControl(optimizer = optim, 
                                           optArgs = list(method = "BFGS"))) 
}
```

```{r}

# --- PLOT RESIDUALS --- #

qqnorm(resid(model))
qqline(resid(model))

create.res.vs.fit.ecosystems(model,
                             data_for_analysis)
```

```{r}

# --- SHOW MODEL SUMMARY --- #

print(summary(model), digits = 3)
```


```{r eval = (distribution_selected == "gaussian"), echo = (distribution_selected == "gaussian")}

# --- PERFORM ANOVA (GAUSSIAN) --- #

ANOVA = anova(model) %>%
  print()
```

```{r eval = (distribution_selected == "tweedie"), echo = (distribution_selected == "tweedie")}

# --- PERFORM ANOVA --- #

ANOVA = car::Anova(model, type = "III") %>%
  print()
```

```{r}

# --- ESTIMATE MARGINAL MEANS --- #

emmeans_output = emmeans(model,
                         specs = pairwise ~ size:connection,
                         adjust = "tukey",
                         bias.adj = TRUE,
                         lmer.df = "satterthwaite")
```

```{r class.source = 'fold-show'}

# --- CODE THE CONTRAST LEVELS --- #

emmeans_output

L_unconnected = c(1, 0, 0, 0, 0, 0)
M_unconnected = c(0, 1, 0, 0, 0, 0)
S_unconnected = c(0, 0, 1, 0, 0, 0)
L_connected = c(0, 0, 0, 1, 0, 0)
M_connected = c(0, 0, 0, 0, 1, 0)
S_connected = c(0, 0, 0, 0, 0, 1)
```

```{r eval = (response_variable_selected %in% c("species_richness", "shannon", "evenness_pielou"))}

# --- CALCULATE CONTRASTS YOU ARE INTERESTED IN (T-RATIO, USED FOR RESPONSE VARIABLES WITH NORMAL DISTRIBUTION)--- #

n_of_digits = 3
contrasts = contrast(emmeans_output, 
         method = list("small connection effect" = S_connected - S_unconnected,
                       "medium connection effect" = M_connected - M_unconnected,
                       "large connection effect" = L_connected - L_unconnected,
                       "Size effect in unconnected (L - S)" = L_unconnected - S_unconnected,
                       "Size effect in unconnected (M - S)" = M_unconnected - S_unconnected,
                       "Size effect in connected (L - S)" = L_connected - S_connected,
                       "Size effect in connected (M - S)" = M_connected - S_connected)) %>%
  as.data.frame() %>%
  mutate(p.value = round(p.value, digits = n_of_digits),
         estimate = round(estimate, digits = n_of_digits),
         SE = round(SE, digits = n_of_digits),
         df = round(df, digits = n_of_digits),
         t.ratio = round(t.ratio, digits = n_of_digits),
         e = "",
         e = ifelse(p.value > 0.1, 
                           "",
                           e),
         e = ifelse(p.value < 0.05, 
                           "*",
                           e),
         e = ifelse(p.value < 0.01, 
                           "**",
                           e),
         e = ifelse(p.value < 0.001, 
                           "***",
                           e)) %>%
  rename(" " = e)
```

```{r eval = (response_variable_selected %in% c("bioarea_mm2_per_ml", "indiv_per_ml", "median_body_size_µm2"))}

# --- CALCULATE CONTRASTS YOU ARE INTERESTED IN (Z RATIO, USED FOR REPONSE VARIABLES WITH TWEEDIE DISRIBUTION) --- #

n_of_digits = 3
contrasts = contrast(emmeans_output, 
         method = list("small connection effect" = S_connected - S_unconnected,
                       "medium connection effect" = M_connected - M_unconnected,
                       "large connection effect" = L_connected - L_unconnected,
                       "Size effect in unconnected (L - S)" = L_unconnected - S_unconnected,
                       "Size effect in unconnected (M - S)" = M_unconnected - S_unconnected,
                       "Size effect in connected (L - S)" = L_connected - S_connected,
                       "Size effect in connected (M - S)" = M_connected - S_connected)) %>%
  as.data.frame() %>%
  mutate(p.value = round(p.value, digits = n_of_digits),
         estimate = round(estimate, digits = n_of_digits),
         SE = round(SE, digits = n_of_digits),
         df = round(df, digits = n_of_digits),
         z.ratio = round(z.ratio, digits = n_of_digits),
         e = "",
         e = ifelse(p.value > 0.1, 
                           "",
                           e),
         e = ifelse(p.value < 0.05, 
                           "*",
                           e),
         e = ifelse(p.value < 0.01, 
                           "**",
                           e),
         e = ifelse(p.value < 0.001, 
                           "***",
                           e)) %>%
  rename(" " = e)
```
</details>

<details open = "open">
<summary>Show results</summary>
```{r}

# --- SHOW RESULTS --- #

ANOVA
contrasts
```
</details>