---
title: "Untitled"
output: html_document
date: "2023-11-20"
editor_options: 
  chunk_output_type: console
---

```{r results=FALSE}

# --- CONSTRUCT ECOSYSTEM BIOMASS PLOTS --- #

# Set parameters

response_variable = "bioarea_mm2_per_ml"
ecosystem_size_and_trophy_p_1 = c("large autotrophic",
                                  "small heterotrophic")
ecosystem_size_and_trophy_p_2 = c("medium autotrophic",
                                  "medium heterotrophic")
ecosystem_size_and_trophy_p_3 = c("large heterotrophic",
                                  "small autotrophic")
legend_row_n_input = 2
y_min = 0
y_max = 21

# Prepare data for plotting

data_plot_1 = ds_ecosystems %>%
  filter(ecosystem_size_and_trophy %in% ecosystem_size_and_trophy_p_1)

data_plot_2 = ds_ecosystems %>%
  filter(ecosystem_size_and_trophy %in% ecosystem_size_and_trophy_p_2)

data_plot_3 = ds_ecosystems %>%
  filter(ecosystem_size_and_trophy %in% ecosystem_size_and_trophy_p_3)

# Construct plots
    
p_1 = plot.ecosystems.points.paper(data_plot_1,
                             response_variable,
                             legend_row_n_input) +
  theme(plot.margin = unit(c(ggarrange_margin_left,
                             ggarrange_margin_right,
                             ggarrange_margin_bottom,
                             ggarrange_margin_left),
                           "cm")) +
  ylim(y_min, y_max)
  
p_2 = plot.ecosystems.points.paper(data_plot_2,
                             response_variable,
                             legend_row_n_input) +
  theme(plot.margin = unit(c(ggarrange_margin_left,
                             ggarrange_margin_right,
                             ggarrange_margin_bottom,
                             ggarrange_margin_left),
                             "cm")) + 
  ylim(y_min, y_max)

p_3 = plot.ecosystems.points.paper(data_plot_3,
                             response_variable,
                             legend_row_n_input) +
  theme(plot.margin = unit(c(ggarrange_margin_left,
                             ggarrange_margin_right,
                             ggarrange_margin_bottom,
                             ggarrange_margin_left),
                             "cm")) + 
  ylim(y_min, y_max)

# Combine plots
  
p_combined = ggarrange(p_1 +
                         rremove("xlab") +
                         theme(axis.text.x = element_blank(),
                               axis.ticks.x = element_blank()),
                       p_2 +
                         rremove("xlab") +
                         theme(axis.text.x = element_blank(),
                               axis.ticks.x = element_blank(),
                               legend.position = "none"),
                       p_3 +
                         scale_x_continuous(breaks = unique(data_plot_2$day)) +
                         theme(legend.position = "none"),
                       heights = c(0.95, 0.70, 0.8),
                       nrow = 3,
                       align = "v",
                       labels = c("autotrophic-dominated", 
                                  "equally-dominated", 
                                  "heterotrophic-dominated"),
                       label.x = c(-0.080, -0.05, -0.095),
                       label.y = c(0.70, 0.977, 0.979))
```

```{r fig.height = figures_height_rmd_output}

# --- SHOW ECOSYSTEM BIOMASS PLOTS --- #

p_combined
```

```{r results=FALSE}

# --- SAVE ECOSYSTEM BIOMASS PLOTS --- #

# Generate the image where to save the plot

pdf(file = here("..",
                "3_results", 
                "figures", 
                "paper", 
                "ecosystems_biomass.pdf"),
    width = paper_width_inches,
    height = paper_height_inches)

# Save image to the file

p_combined

# Close the current graphics device to properly save the image

dev.off()
```