---
title: "PhD Chapter 2 - AHSize"
author: "Emanuele Giacomuzzo"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M')`"
editor_options: 
  chunk_output_type: console
---

###### Small ecosystems

```{r class.source = 'fold-show'}
print_dominance("Small heterotrophic unconnected")
print_dominance("Small heterotrophic connected")
```

```{r warning=FALSE}
for(time_point_i in 2:4){
    
    print(paste("Time point ", time_point_i))
    
    p = ds_species_effect_sizes_LRR %>%
      filter(ecosystem_type == "Small heterotrophic connected",
             time_point == time_point_i,
             species != "Eug") %>%
      ggplot(aes(x = species,
                 y = effect_size)) + 
      geom_pointrange(aes(ymin = lower_95_CI, ymax = upper_95_CI)) + 
      geom_hline(yintercept = 0, linetype = "dotted") +
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            legend.position = legend_position,
            legend.key.width = unit(legend_width_cm, "cm"))
    
    print(p)
    
  }
```


###### Medium ecosystems

```{r class.source = 'fold-show'}
print_dominance("Medium heterotrophic unconnected")
print_dominance("Medium heterotrophic connected")
```

```{r warning=FALSE}
for(time_point_i in 2:4){
    
    print(paste("Time point ", time_point_i))
    
    p = ds_species_effect_sizes_LRR %>%
      filter(ecosystem_type == "Medium heterotrophic connected",
             time_point == time_point_i,
             species != "Eug") %>%
      ggplot(aes(x = species,
                 y = effect_size)) + 
      geom_pointrange(aes(ymin = lower_95_CI, ymax = upper_95_CI)) + 
      geom_hline(yintercept = 0, linetype = "dotted") +
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            legend.position = legend_position,
            legend.key.width = unit(legend_width_cm, "cm"))
    
    print(p)
    
  }
```

###### Large ecosystems

```{r class.source = 'fold-show'}
print_dominance("Large heterotrophic unconnected")
print_dominance("Large heterotrophic connected")
```

```{r warning=FALSE}
for(time_point_i in 2:4){
    
    print(paste("Time point ", time_point_i))
    
    p = ds_species_effect_sizes_LRR %>%
      filter(ecosystem_type == "Large heterotrophic connected",
             time_point == time_point_i,
             species != "Eug") %>%
      ggplot(aes(x = species,
                 y = effect_size)) + 
      geom_pointrange(aes(ymin = lower_95_CI, ymax = upper_95_CI)) + 
      geom_hline(yintercept = 0, linetype = "dotted") +
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            legend.position = legend_position,
            legend.key.width = unit(legend_width_cm, "cm"))
    
    print(p)
    
  }
```

###### Together

The connection in small ecosystems increases Ble (t3) and Pau and Cep (t4). In medium ecosystems it increases Ble (t3), Spi (t4), and decreases Cep and Col (t5). In large ecosystems it increases Col and Ble (t2), and increases Spi (t5).