---
title: "Untitled"
output: html_document
date: "2023-11-20"
editor_options: 
  chunk_output_type: console
---

Figure 3. The connection to another patch increased the biomass of the autotrophic ecosystems and decreased the biomass of the heterotrophic ecosystems in both (a) Autotrophic Dominated and (b) Heterotrophic Dominated meta-ecosystems

```{r results=FALSE}

# --- CONSTRUCT ECOSYSTEM BIOMASS PLOTS --- #

# Set parameters

response_variable = "bioarea_mm2_per_ml"
ecosystem_size_and_trophy_p_1 = c("Large autotrophic",
                                  "Small heterotrophic")
ecosystem_size_and_trophy_p_2 = c("Large heterotrophic",
                                  "Small autotrophic")
legend_row_n_input = 2
y_min = 0
y_max = 21

# Prepare data for plotting

data_plot_1 = ds_ecosystems %>%
  filter(ecosystem_size_and_trophy %in% ecosystem_size_and_trophy_p_1)

data_plot_2 = ds_ecosystems %>%
  filter(ecosystem_size_and_trophy %in% ecosystem_size_and_trophy_p_2)

# Construct plots
    
p_1 = plot.ecosystems.points(data_plot_1,
                             response_variable,
                             legend_row_n_input) +
  theme(plot.margin = unit(c(ggarrange_margin_left,
                             ggarrange_margin_right,
                             ggarrange_margin_bottom,
                             ggarrange_margin_left),
                           "cm")) +
  ylim(y_min, y_max)
  
p_2 = plot.ecosystems.points(data_plot_2,
                             response_variable,
                             legend_row_n_input) +
  theme(plot.margin = unit(c(ggarrange_margin_left,
                             ggarrange_margin_right,
                             ggarrange_margin_bottom,
                             ggarrange_margin_left),
                             "cm")) + 
  ylim(y_min, y_max)

# Combine plots
  
p_combined = ggarrange(p_1 +
                         rremove("xlab") +
                         theme(axis.text.x = element_blank(),
                               axis.ticks.x = element_blank()),
                       p_2 +
                         scale_x_continuous(breaks = unique(data_plot_2$day)),
                       heights = c(0.8, 0.8, 1),
                       nrow = 2,
                       align = "v",
                       labels = c("AD", "HD"),
                       label.x = 0.07,
                       label.y = 0.77)
```

```{r fig.height = figures_height_rmd_output}

# --- SHOW ECOSYSTEM BIOMASS PLOTS --- #

p_combined
```

```{r results=FALSE}

# --- SAVE ECOSYSTEM BIOMASS PLOTS --- #

# Generate the PNG image where to save the plot

png(file = here("3_results", "figures", "paper", "ecosystems_biomass.png"),
    width = paper_width,
    height = paper_height,
    units = paper_units,
    res = paper_res)

# Save image to the file

p_combined

# Close the current graphics device to properly save the PNG image

dev.off()
```